artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/NayanBhandari02/Data/raw/refs/heads/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: C:\Users\Nayan Bhandari\Desktop\NLP\TextSummarizer-NLP-\artifacts\data_ingestion\samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: C:\Users\Nayan Bhandari\Desktop\NLP\TextSummarizer-NLP-\artifacts\data_transformation\samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail